"""Canonical audit event names. Keep these stable: they are queried by compliance views."""

DOCUMENT_UPLOADED = "document.uploaded"
DOCUMENT_STATUS_CHANGED = "document.status_changed"
DOCUMENT_LINKED = "document.linked"
EXTRACTION_COMPLETED = "extraction.completed"
EXTRACTION_FAILED = "extraction.failed"
ENTITY_EXTRACTED = "entity.extracted"
VALIDATION_STARTED = "validation.started"
VALIDATION_COMPLETED = "validation.completed"
VALIDATION_FAILED = "validation.failed"
FLAG_RAISED = "flag.raised"
ROUTING_DECIDED = "routing.decided"
REVIEW_ACTION = "review.action"
RULE_PACK_CREATED = "rule_pack.created"
RULE_PACK_UPDATED = "rule_pack.updated"
USER_REGISTERED = "user.registered"
USER_LOGIN = "user.login"
